[tool.poetry]
name = "snack_tracker_project"
version = "0.1.0"
description = ""
authors = ["micgreene <mgreene11111@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
